language: java

jdk:
  - openjdk11

notifications:
  email: false

script:
  - "mvn clean install -Dmaven.javadoc.skip=true -Dmaven.test.skip=true -B -V"
  - "mvn clean install -Dforce.java9.compilation=true -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -B -V"