/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_violetlib_aqua_AquaImageFactory_GenerateDisabledLightFilter */

#ifndef _Included_org_violetlib_aqua_AquaImageFactory_GenerateDisabledLightFilter
#define _Included_org_violetlib_aqua_AquaImageFactory_GenerateDisabledLightFilter
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
