/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_violetlib_aqua_AquaNativeSupport */

#ifndef _Included_org_violetlib_aqua_AquaNativeSupport
#define _Included_org_violetlib_aqua_AquaNativeSupport
#ifdef __cplusplus
extern "C" {
#endif
#undef org_violetlib_aqua_AquaNativeSupport_EXPECTED_NATIVE_CODE_VERSION
#define org_violetlib_aqua_AquaNativeSupport_EXPECTED_NATIVE_CODE_VERSION 2L
/*
 * Class:     org_violetlib_aqua_AquaNativeSupport
 * Method:    setup
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_violetlib_aqua_AquaNativeSupport_setup
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_violetlib_aqua_AquaNativeSupport
 * Method:    nativeGetNativeCodeVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_violetlib_aqua_AquaNativeSupport_nativeGetNativeCodeVersion
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
