/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_violetlib_aqua_AquaSheetSupport_SheetCloser */

#ifndef _Included_org_violetlib_aqua_AquaSheetSupport_SheetCloser
#define _Included_org_violetlib_aqua_AquaSheetSupport_SheetCloser
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
