/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_violetlib_aqua_AquaUtils_ShadowMaker */

#ifndef _Included_org_violetlib_aqua_AquaUtils_ShadowMaker
#define _Included_org_violetlib_aqua_AquaUtils_ShadowMaker
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
