/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_violetlib_aqua_AquaIcon */

#ifndef _Included_org_violetlib_aqua_AquaIcon
#define _Included_org_violetlib_aqua_AquaIcon
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_violetlib_aqua_AquaIcon
 * Method:    nativeRenderIcon
 * Signature: (I[[II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_violetlib_aqua_AquaIcon_nativeRenderIcon
  (JNIEnv *, jclass, jint, jobjectArray, jint);

#ifdef __cplusplus
}
#endif
#endif
