/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_violetlib_aqua_AquaIcon_RecyclableIconImageSingleton */

#ifndef _Included_org_violetlib_aqua_AquaIcon_RecyclableIconImageSingleton
#define _Included_org_violetlib_aqua_AquaIcon_RecyclableIconImageSingleton
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
