/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_violetlib_aqua_AquaSheetSupport */

#ifndef _Included_org_violetlib_aqua_AquaSheetSupport
#define _Included_org_violetlib_aqua_AquaSheetSupport
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_violetlib_aqua_AquaSheetSupport
 * Method:    nativeDisplayAsSheet
 * Signature: (Ljava/awt/Window;)I
 */
JNIEXPORT jint JNICALL Java_org_violetlib_aqua_AquaSheetSupport_nativeDisplayAsSheet
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
