/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_violetlib_aqua_fc_OSXFile_MyImageProvider */

#ifndef _Included_org_violetlib_aqua_fc_OSXFile_MyImageProvider
#define _Included_org_violetlib_aqua_fc_OSXFile_MyImageProvider
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
