/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_violetlib_aqua_AquaUtils_GrayUIResource */

#ifndef _Included_org_violetlib_aqua_AquaUtils_GrayUIResource
#define _Included_org_violetlib_aqua_AquaUtils_GrayUIResource
#ifdef __cplusplus
extern "C" {
#endif
#undef org_violetlib_aqua_AquaUtils_GrayUIResource_serialVersionUID
#define org_violetlib_aqua_AquaUtils_GrayUIResource_serialVersionUID 118526816881161077LL
#undef org_violetlib_aqua_AquaUtils_GrayUIResource_FACTOR
#define org_violetlib_aqua_AquaUtils_GrayUIResource_FACTOR 0.7
#ifdef __cplusplus
}
#endif
#endif
