/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_violetlib_aqua_AquaNativeColorChooser */

#ifndef _Included_org_violetlib_aqua_AquaNativeColorChooser
#define _Included_org_violetlib_aqua_AquaNativeColorChooser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_violetlib_aqua_AquaNativeColorChooser
 * Method:    create
 * Signature: (Lorg/violetlib/aqua/SharedColorChooserOwner;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_violetlib_aqua_AquaNativeColorChooser_create
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_violetlib_aqua_AquaNativeColorChooser
 * Method:    show
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_violetlib_aqua_AquaNativeColorChooser_show
  (JNIEnv *, jclass);

/*
 * Class:     org_violetlib_aqua_AquaNativeColorChooser
 * Method:    hide
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_violetlib_aqua_AquaNativeColorChooser_hide
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
