/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_violetlib_aqua_AquaVibrantSupport_VisualEffectViewPeerImpl */

#ifndef _Included_org_violetlib_aqua_AquaVibrantSupport_VisualEffectViewPeerImpl
#define _Included_org_violetlib_aqua_AquaVibrantSupport_VisualEffectViewPeerImpl
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
