/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_violetlib_aqua_AquaVibrantSupport */

#ifndef _Included_org_violetlib_aqua_AquaVibrantSupport
#define _Included_org_violetlib_aqua_AquaVibrantSupport
#ifdef __cplusplus
extern "C" {
#endif
#undef org_violetlib_aqua_AquaVibrantSupport_LIGHT_STYLE
#define org_violetlib_aqua_AquaVibrantSupport_LIGHT_STYLE 0L
#undef org_violetlib_aqua_AquaVibrantSupport_DARK_STYLE
#define org_violetlib_aqua_AquaVibrantSupport_DARK_STYLE 1L
#undef org_violetlib_aqua_AquaVibrantSupport_SIDEBAR_STYLE
#define org_violetlib_aqua_AquaVibrantSupport_SIDEBAR_STYLE 2L
#undef org_violetlib_aqua_AquaVibrantSupport_TITLE_BAR_STYLE
#define org_violetlib_aqua_AquaVibrantSupport_TITLE_BAR_STYLE 3L
#undef org_violetlib_aqua_AquaVibrantSupport_MENU_STYLE
#define org_violetlib_aqua_AquaVibrantSupport_MENU_STYLE 4L
#undef org_violetlib_aqua_AquaVibrantSupport_POPOVER_STYLE
#define org_violetlib_aqua_AquaVibrantSupport_POPOVER_STYLE 5L
#undef org_violetlib_aqua_AquaVibrantSupport_MEDIUM_LIGHT_STYLE
#define org_violetlib_aqua_AquaVibrantSupport_MEDIUM_LIGHT_STYLE 6L
#undef org_violetlib_aqua_AquaVibrantSupport_ULTRA_DARK_STYLE
#define org_violetlib_aqua_AquaVibrantSupport_ULTRA_DARK_STYLE 7L
#undef org_violetlib_aqua_AquaVibrantSupport_SHEET_STYLE
#define org_violetlib_aqua_AquaVibrantSupport_SHEET_STYLE 8L
/*
 * Class:     org_violetlib_aqua_AquaVibrantSupport
 * Method:    setupVisualEffectWindow
 * Signature: (Ljava/awt/Window;IZ)I
 */
JNIEXPORT jint JNICALL Java_org_violetlib_aqua_AquaVibrantSupport_setupVisualEffectWindow
  (JNIEnv *, jclass, jobject, jint, jboolean);

/*
 * Class:     org_violetlib_aqua_AquaVibrantSupport
 * Method:    removeVisualEffectWindow
 * Signature: (Ljava/awt/Window;)I
 */
JNIEXPORT jint JNICALL Java_org_violetlib_aqua_AquaVibrantSupport_removeVisualEffectWindow
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_violetlib_aqua_AquaVibrantSupport
 * Method:    nativeCreateVisualEffectView
 * Signature: (Ljava/awt/Window;IZ)J
 */
JNIEXPORT jlong JNICALL Java_org_violetlib_aqua_AquaVibrantSupport_nativeCreateVisualEffectView
  (JNIEnv *, jclass, jobject, jint, jboolean);

/*
 * Class:     org_violetlib_aqua_AquaVibrantSupport
 * Method:    setViewFrame
 * Signature: (JIIIII)I
 */
JNIEXPORT jint JNICALL Java_org_violetlib_aqua_AquaVibrantSupport_setViewFrame
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jint);

/*
 * Class:     org_violetlib_aqua_AquaVibrantSupport
 * Method:    nativeUpdateSelectionBackgrounds
 * Signature: (J[I)I
 */
JNIEXPORT jint JNICALL Java_org_violetlib_aqua_AquaVibrantSupport_nativeUpdateSelectionBackgrounds
  (JNIEnv *, jclass, jlong, jintArray);

/*
 * Class:     org_violetlib_aqua_AquaVibrantSupport
 * Method:    disposeVisualEffectView
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_violetlib_aqua_AquaVibrantSupport_disposeVisualEffectView
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
