/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_violetlib_aqua_AquaImageFactory */

#ifndef _Included_org_violetlib_aqua_AquaImageFactory
#define _Included_org_violetlib_aqua_AquaImageFactory
#ifdef __cplusplus
extern "C" {
#endif
#undef org_violetlib_aqua_AquaImageFactory_kAlertIconSize
#define org_violetlib_aqua_AquaImageFactory_kAlertIconSize 64L
/*
 * Class:     org_violetlib_aqua_AquaImageFactory
 * Method:    getNativeImage
 * Signature: (Ljava/lang/String;II)Ljava/awt/Image;
 */
JNIEXPORT jobject JNICALL Java_org_violetlib_aqua_AquaImageFactory_getNativeImage
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     org_violetlib_aqua_AquaImageFactory
 * Method:    nativeRenderImageFile
 * Signature: (Ljava/lang/String;[[III)Z
 */
JNIEXPORT jboolean JNICALL Java_org_violetlib_aqua_AquaImageFactory_nativeRenderImageFile
  (JNIEnv *, jclass, jstring, jobjectArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
