/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_violetlib_aqua_fc_OSXFile_StreamCollector */

#ifndef _Included_org_violetlib_aqua_fc_OSXFile_StreamCollector
#define _Included_org_violetlib_aqua_fc_OSXFile_StreamCollector
#ifdef __cplusplus
extern "C" {
#endif
#undef org_violetlib_aqua_fc_OSXFile_StreamCollector_MIN_PRIORITY
#define org_violetlib_aqua_fc_OSXFile_StreamCollector_MIN_PRIORITY 1L
#undef org_violetlib_aqua_fc_OSXFile_StreamCollector_NORM_PRIORITY
#define org_violetlib_aqua_fc_OSXFile_StreamCollector_NORM_PRIORITY 5L
#undef org_violetlib_aqua_fc_OSXFile_StreamCollector_MAX_PRIORITY
#define org_violetlib_aqua_fc_OSXFile_StreamCollector_MAX_PRIORITY 10L
#ifdef __cplusplus
}
#endif
#endif
