/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_violetlib_aqua_AquaIcon_SystemIcon */

#ifndef _Included_org_violetlib_aqua_AquaIcon_SystemIcon
#define _Included_org_violetlib_aqua_AquaIcon_SystemIcon
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
