/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_violetlib_aqua_fc_OSXFile */

#ifndef _Included_org_violetlib_aqua_fc_OSXFile
#define _Included_org_violetlib_aqua_fc_OSXFile
#ifdef __cplusplus
extern "C" {
#endif
#undef org_violetlib_aqua_fc_OSXFile_FILE_TYPE_ALIAS
#define org_violetlib_aqua_fc_OSXFile_FILE_TYPE_ALIAS 2L
#undef org_violetlib_aqua_fc_OSXFile_FILE_TYPE_DIRECTORY
#define org_violetlib_aqua_fc_OSXFile_FILE_TYPE_DIRECTORY 1L
#undef org_violetlib_aqua_fc_OSXFile_FILE_TYPE_FILE
#define org_violetlib_aqua_fc_OSXFile_FILE_TYPE_FILE 0L
#undef org_violetlib_aqua_fc_OSXFile_FILE_TYPE_UNKNOWN
#define org_violetlib_aqua_fc_OSXFile_FILE_TYPE_UNKNOWN -1L
#undef org_violetlib_aqua_fc_OSXFile_kLSItemInfoIsPlainFile
#define org_violetlib_aqua_fc_OSXFile_kLSItemInfoIsPlainFile 1L
#undef org_violetlib_aqua_fc_OSXFile_kLSItemInfoIsPackage
#define org_violetlib_aqua_fc_OSXFile_kLSItemInfoIsPackage 2L
#undef org_violetlib_aqua_fc_OSXFile_kLSItemInfoIsApplication
#define org_violetlib_aqua_fc_OSXFile_kLSItemInfoIsApplication 4L
#undef org_violetlib_aqua_fc_OSXFile_kLSItemInfoIsContainer
#define org_violetlib_aqua_fc_OSXFile_kLSItemInfoIsContainer 8L
#undef org_violetlib_aqua_fc_OSXFile_kLSItemInfoIsAliasFile
#define org_violetlib_aqua_fc_OSXFile_kLSItemInfoIsAliasFile 16L
#undef org_violetlib_aqua_fc_OSXFile_kLSItemInfoIsSymlink
#define org_violetlib_aqua_fc_OSXFile_kLSItemInfoIsSymlink 32L
#undef org_violetlib_aqua_fc_OSXFile_kLSItemInfoIsInvisible
#define org_violetlib_aqua_fc_OSXFile_kLSItemInfoIsInvisible 64L
#undef org_violetlib_aqua_fc_OSXFile_kLSItemInfoIsNativeApp
#define org_violetlib_aqua_fc_OSXFile_kLSItemInfoIsNativeApp 128L
#undef org_violetlib_aqua_fc_OSXFile_kLSItemInfoIsClassicApp
#define org_violetlib_aqua_fc_OSXFile_kLSItemInfoIsClassicApp 256L
#undef org_violetlib_aqua_fc_OSXFile_kLSItemInfoAppPrefersNative
#define org_violetlib_aqua_fc_OSXFile_kLSItemInfoAppPrefersNative 512L
#undef org_violetlib_aqua_fc_OSXFile_kLSItemInfoAppPrefersClassic
#define org_violetlib_aqua_fc_OSXFile_kLSItemInfoAppPrefersClassic 1024L
#undef org_violetlib_aqua_fc_OSXFile_kLSItemInfoAppIsScriptable
#define org_violetlib_aqua_fc_OSXFile_kLSItemInfoAppIsScriptable 2048L
#undef org_violetlib_aqua_fc_OSXFile_kLSItemInfoIsVolume
#define org_violetlib_aqua_fc_OSXFile_kLSItemInfoIsVolume 4096L
#undef org_violetlib_aqua_fc_OSXFile_kLSItemInfoExtensionIsHidden
#define org_violetlib_aqua_fc_OSXFile_kLSItemInfoExtensionIsHidden 1048576L
#undef org_violetlib_aqua_fc_OSXFile_SIDEBAR_FAVORITES
#define org_violetlib_aqua_fc_OSXFile_SIDEBAR_FAVORITES 0L
#undef org_violetlib_aqua_fc_OSXFile_SIDEBAR_VOLUMES
#define org_violetlib_aqua_fc_OSXFile_SIDEBAR_VOLUMES 1L
/*
 * Class:     org_violetlib_aqua_fc_OSXFile
 * Method:    nativeGetFileType
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_violetlib_aqua_fc_OSXFile_nativeGetFileType
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_violetlib_aqua_fc_OSXFile
 * Method:    nativeResolveAlias
 * Signature: (Ljava/lang/String;Z)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_violetlib_aqua_fc_OSXFile_nativeResolveAlias__Ljava_lang_String_2Z
  (JNIEnv *, jclass, jstring, jboolean);

/*
 * Class:     org_violetlib_aqua_fc_OSXFile
 * Method:    nativeResolveAlias
 * Signature: ([BZ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_violetlib_aqua_fc_OSXFile_nativeResolveAlias___3BZ
  (JNIEnv *, jclass, jbyteArray, jboolean);

/*
 * Class:     org_violetlib_aqua_fc_OSXFile
 * Method:    nativeGetLabel
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_violetlib_aqua_fc_OSXFile_nativeGetLabel
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_violetlib_aqua_fc_OSXFile
 * Method:    nativeGetKindString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_violetlib_aqua_fc_OSXFile_nativeGetKindString
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_violetlib_aqua_fc_OSXFile
 * Method:    nativeGetBasicItemInfoFlags
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_violetlib_aqua_fc_OSXFile_nativeGetBasicItemInfoFlags
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_violetlib_aqua_fc_OSXFile
 * Method:    nativeGetDisplayName
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_violetlib_aqua_fc_OSXFile_nativeGetDisplayName
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_violetlib_aqua_fc_OSXFile
 * Method:    nativeGetLastUsedDate
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_violetlib_aqua_fc_OSXFile_nativeGetLastUsedDate
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_violetlib_aqua_fc_OSXFile
 * Method:    nativeExecuteSavedSearch
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_violetlib_aqua_fc_OSXFile_nativeExecuteSavedSearch
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_violetlib_aqua_fc_OSXFile
 * Method:    nativeGetSidebarFiles
 * Signature: (III)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_org_violetlib_aqua_fc_OSXFile_nativeGetSidebarFiles
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_violetlib_aqua_fc_OSXFile
 * Method:    nativeRenderFileImage
 * Signature: (Ljava/lang/String;ZZ[[III)Z
 */
JNIEXPORT jboolean JNICALL Java_org_violetlib_aqua_fc_OSXFile_nativeRenderFileImage
  (JNIEnv *, jclass, jstring, jboolean, jboolean, jobjectArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
