/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_violetlib_jnr_aqua_impl_NativeSupport */

#ifndef _Included_org_violetlib_jnr_aqua_impl_NativeSupport
#define _Included_org_violetlib_jnr_aqua_impl_NativeSupport
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_violetlib_jnr_aqua_impl_NativeSupport
 * Method:    getJavaRuntimeSupportVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_violetlib_jnr_aqua_impl_NativeSupport_getJavaRuntimeSupportVersion
  (JNIEnv *, jclass);

/*
 * Class:     org_violetlib_jnr_aqua_impl_NativeSupport
 * Method:    syslog
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_violetlib_jnr_aqua_impl_NativeSupport_syslog
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
