/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_violetlib_jnr_aqua_coreui_CoreUIPainter_TitleBarRenderer */

#ifndef _Included_org_violetlib_jnr_aqua_coreui_CoreUIPainter_TitleBarRenderer
#define _Included_org_violetlib_jnr_aqua_coreui_CoreUIPainter_TitleBarRenderer
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
