/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_violetlib_jnr_aqua_coreui_CoreUIPainter */

#ifndef _Included_org_violetlib_jnr_aqua_coreui_CoreUIPainter
#define _Included_org_violetlib_jnr_aqua_coreui_CoreUIPainter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_violetlib_jnr_aqua_coreui_CoreUIPainter
 * Method:    nativePaint
 * Signature: ([IIIFF[Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_org_violetlib_jnr_aqua_coreui_CoreUIPainter_nativePaint
  (JNIEnv *, jclass, jintArray, jint, jint, jfloat, jfloat, jobjectArray);

/*
 * Class:     org_violetlib_jnr_aqua_coreui_CoreUIPainter
 * Method:    nativeJRSPaint
 * Signature: ([IIIFF[Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_org_violetlib_jnr_aqua_coreui_CoreUIPainter_nativeJRSPaint
  (JNIEnv *, jclass, jintArray, jint, jint, jfloat, jfloat, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
