/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_violetlib_jnr_aqua_impl_AquaNativePainter */

#ifndef _Included_org_violetlib_jnr_aqua_impl_AquaNativePainter
#define _Included_org_violetlib_jnr_aqua_impl_AquaNativePainter
#ifdef __cplusplus
extern "C" {
#endif
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_NSRoundedBezelStyle
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_NSRoundedBezelStyle 1L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_NSRegularSquareBezelStyle
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_NSRegularSquareBezelStyle 2L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_NSThickSquareBezelStyle
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_NSThickSquareBezelStyle 3L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_NSThickerSquareBezelStyle
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_NSThickerSquareBezelStyle 4L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_NSDisclosureBezelStyle
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_NSDisclosureBezelStyle 5L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_NSShadowlessSquareBezelStyle
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_NSShadowlessSquareBezelStyle 6L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_NSCircularBezelStyle
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_NSCircularBezelStyle 7L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_NSTexturedSquareBezelStyle
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_NSTexturedSquareBezelStyle 8L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_NSHelpButtonBezelStyle
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_NSHelpButtonBezelStyle 9L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_NSSmallSquareBezelStyle
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_NSSmallSquareBezelStyle 10L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_NSTexturedRoundedBezelStyle
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_NSTexturedRoundedBezelStyle 11L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_NSRoundRectBezelStyle
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_NSRoundRectBezelStyle 12L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_NSRecessedBezelStyle
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_NSRecessedBezelStyle 13L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_NSRoundedDisclosureBezelStyle
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_NSRoundedDisclosureBezelStyle 14L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_NSInlineBezelStyle
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_NSInlineBezelStyle 15L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_NSMomentaryLightButton
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_NSMomentaryLightButton 0L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_NSPushOnPushOffButton
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_NSPushOnPushOffButton 1L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_NSToggleButton
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_NSToggleButton 2L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_NSSwitchButton
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_NSSwitchButton 3L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_NSRadioButton
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_NSRadioButton 4L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_NSMomentaryChangeButton
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_NSMomentaryChangeButton 5L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_NSOnOffButton
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_NSOnOffButton 6L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_NSMomentaryPushInButton
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_NSMomentaryPushInButton 7L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_NSAcceleratorButton
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_NSAcceleratorButton 8L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_NSMultiLevelAcceleratorButton
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_NSMultiLevelAcceleratorButton 9L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_NSGradientNone
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_NSGradientNone 0L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_NSGradientConcaveWeak
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_NSGradientConcaveWeak 1L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_NSGradientConcaveStrong
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_NSGradientConcaveStrong 2L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_NSGradientConvexWeak
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_NSGradientConvexWeak 3L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_NSGradientConvexStrong
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_NSGradientConvexStrong 4L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_TextFieldNormal
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_TextFieldNormal 0L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_TextFieldRound
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_TextFieldRound 1L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_TextFieldSearch
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_TextFieldSearch 2L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_TextFieldSearchWithCancel
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_TextFieldSearchWithCancel 3L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_TextFieldSearchWithMenu
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_TextFieldSearchWithMenu 4L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_TextFieldSearchWithMenuAndCancel
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_TextFieldSearchWithMenuAndCancel 5L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_NSSegmentStyleAutomatic
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_NSSegmentStyleAutomatic 0L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_NSSegmentStyleRounded
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_NSSegmentStyleRounded 1L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_NSSegmentStyleTexturedRounded
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_NSSegmentStyleTexturedRounded 2L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_NSSegmentStyleRoundRect
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_NSSegmentStyleRoundRect 3L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_NSSegmentStyleTexturedSquare
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_NSSegmentStyleTexturedSquare 4L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_NSSegmentStyleCapsule
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_NSSegmentStyleCapsule 5L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_NSSegmentStyleSmallSquare
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_NSSegmentStyleSmallSquare 6L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_NSSegmentStyleSeparated
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_NSSegmentStyleSeparated 8L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_NSNoTitle
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_NSNoTitle 0L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_NSAboveTop
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_NSAboveTop 1L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_NSAtTop
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_NSAtTop 2L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_NSBelowTop
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_NSBelowTop 3L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_NSAboveBottom
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_NSAboveBottom 4L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_NSAtBottom
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_NSAtBottom 5L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_NSBelowBottom
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_NSBelowBottom 6L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_NSLinearSlider
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_NSLinearSlider 0L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_NSCircularSlider
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_NSCircularSlider 1L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_NSLinearSliderRightToLeft
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_NSLinearSliderRightToLeft 1002L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_NSLinearSliderUpsideDown
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_NSLinearSliderUpsideDown 1003L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_NSTickMarkBelow
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_NSTickMarkBelow 0L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_NSTickMarkAbove
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_NSTickMarkAbove 1L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_NSTickMarkLeft
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_NSTickMarkLeft 1L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_NSTickMarkRight
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_NSTickMarkRight 0L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_NSSplitViewDividerStyleThick
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_NSSplitViewDividerStyleThick 1L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_NSSplitViewDividerStyleThin
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_NSSplitViewDividerStyleThin 2L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_NSSplitViewDividerStylePaneSplitter
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_NSSplitViewDividerStylePaneSplitter 3L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_ActiveState
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_ActiveState 0L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_InactiveState
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_InactiveState 1L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_DisabledState
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_DisabledState 2L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_PressedState
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_PressedState 3L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_DefaultState
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_DefaultState 4L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_RolloverState
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_RolloverState 5L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_DisabledInactiveState
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_DisabledInactiveState 6L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_DocumentWindowType
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_DocumentWindowType 0L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_UtilityWindowType
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_UtilityWindowType 1L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_LegacyScrollBar
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_LegacyScrollBar 0L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_OverlayScrollBar
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_OverlayScrollBar 1L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_RolloverOverlayScrollBar
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_RolloverOverlayScrollBar 2L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_SEGMENT_POSITION_FIRST
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_SEGMENT_POSITION_FIRST 0L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_SEGMENT_POSITION_MIDDLE
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_SEGMENT_POSITION_MIDDLE 1L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_SEGMENT_POSITION_LAST
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_SEGMENT_POSITION_LAST 2L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_SEGMENT_POSITION_ONLY
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_SEGMENT_POSITION_ONLY 3L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_SEGMENT_FLAG_IS_SELECTED
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_SEGMENT_FLAG_IS_SELECTED 1L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_SEGMENT_FLAG_IS_LEFT_NEIGHBOR_SELECTED
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_SEGMENT_FLAG_IS_LEFT_NEIGHBOR_SELECTED 2L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_SEGMENT_FLAG_IS_RIGHT_NEIGHBOR_SELECTED
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_SEGMENT_FLAG_IS_RIGHT_NEIGHBOR_SELECTED 4L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_SEGMENT_FLAG_DRAW_LEADING_SEPARATOR
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_SEGMENT_FLAG_DRAW_LEADING_SEPARATOR 8L
#undef org_violetlib_jnr_aqua_impl_AquaNativePainter_SEGMENT_FLAG_DRAW_TRAILING_SEPARATOR
#define org_violetlib_jnr_aqua_impl_AquaNativePainter_SEGMENT_FLAG_DRAW_TRAILING_SEPARATOR 16L
/*
 * Class:     org_violetlib_jnr_aqua_impl_AquaNativePainter
 * Method:    nativePaintIndeterminateProgressIndicator
 * Signature: ([IIIFFIIIZI)V
 */
JNIEXPORT void JNICALL Java_org_violetlib_jnr_aqua_impl_AquaNativePainter_nativePaintIndeterminateProgressIndicator
  (JNIEnv *, jclass, jintArray, jint, jint, jfloat, jfloat, jint, jint, jint, jboolean, jint);

/*
 * Class:     org_violetlib_jnr_aqua_impl_AquaNativePainter
 * Method:    nativePaintProgressIndicator
 * Signature: ([IIIFFIIID)V
 */
JNIEXPORT void JNICALL Java_org_violetlib_jnr_aqua_impl_AquaNativePainter_nativePaintProgressIndicator
  (JNIEnv *, jclass, jintArray, jint, jint, jfloat, jfloat, jint, jint, jint, jdouble);

/*
 * Class:     org_violetlib_jnr_aqua_impl_AquaNativePainter
 * Method:    nativePaintButton
 * Signature: ([IIIFFIIIIZII)V
 */
JNIEXPORT void JNICALL Java_org_violetlib_jnr_aqua_impl_AquaNativePainter_nativePaintButton
  (JNIEnv *, jclass, jintArray, jint, jint, jfloat, jfloat, jint, jint, jint, jint, jboolean, jint, jint);

/*
 * Class:     org_violetlib_jnr_aqua_impl_AquaNativePainter
 * Method:    nativePaintColorWell
 * Signature: ([IIIFFI)V
 */
JNIEXPORT void JNICALL Java_org_violetlib_jnr_aqua_impl_AquaNativePainter_nativePaintColorWell
  (JNIEnv *, jclass, jintArray, jint, jint, jfloat, jfloat, jint);

/*
 * Class:     org_violetlib_jnr_aqua_impl_AquaNativePainter
 * Method:    nativePaintToolBarItemWell
 * Signature: ([IIIFFIZ)V
 */
JNIEXPORT void JNICALL Java_org_violetlib_jnr_aqua_impl_AquaNativePainter_nativePaintToolBarItemWell
  (JNIEnv *, jclass, jintArray, jint, jint, jfloat, jfloat, jint, jboolean);

/*
 * Class:     org_violetlib_jnr_aqua_impl_AquaNativePainter
 * Method:    nativePaintGroupBox
 * Signature: ([IIIFFIIZ)V
 */
JNIEXPORT void JNICALL Java_org_violetlib_jnr_aqua_impl_AquaNativePainter_nativePaintGroupBox
  (JNIEnv *, jclass, jintArray, jint, jint, jfloat, jfloat, jint, jint, jboolean);

/*
 * Class:     org_violetlib_jnr_aqua_impl_AquaNativePainter
 * Method:    nativePaintListBox
 * Signature: ([IIIFFIZZ)V
 */
JNIEXPORT void JNICALL Java_org_violetlib_jnr_aqua_impl_AquaNativePainter_nativePaintListBox
  (JNIEnv *, jclass, jintArray, jint, jint, jfloat, jfloat, jint, jboolean, jboolean);

/*
 * Class:     org_violetlib_jnr_aqua_impl_AquaNativePainter
 * Method:    nativePaintTextField
 * Signature: ([IIIFFIII)V
 */
JNIEXPORT void JNICALL Java_org_violetlib_jnr_aqua_impl_AquaNativePainter_nativePaintTextField
  (JNIEnv *, jclass, jintArray, jint, jint, jfloat, jfloat, jint, jint, jint);

/*
 * Class:     org_violetlib_jnr_aqua_impl_AquaNativePainter
 * Method:    nativePaintSegmentedButton
 * Signature: ([IIIFFIIIIZI)V
 */
JNIEXPORT void JNICALL Java_org_violetlib_jnr_aqua_impl_AquaNativePainter_nativePaintSegmentedButton
  (JNIEnv *, jclass, jintArray, jint, jint, jfloat, jfloat, jint, jint, jint, jint, jboolean, jint, jfloatArray, jintArray);

/*
 * Class:     org_violetlib_jnr_aqua_impl_AquaNativePainter
 * Method:    nativePaintComboBox
 * Signature: ([IIIFFIIII)V
 */
JNIEXPORT void JNICALL Java_org_violetlib_jnr_aqua_impl_AquaNativePainter_nativePaintComboBox
  (JNIEnv *, jclass, jintArray, jint, jint, jfloat, jfloat, jint, jint, jint, jint, jint);

/*
 * Class:     org_violetlib_jnr_aqua_impl_AquaNativePainter
 * Method:    nativePaintPopUpButton
 * Signature: ([IIIFFZIIII)V
 */
JNIEXPORT void JNICALL Java_org_violetlib_jnr_aqua_impl_AquaNativePainter_nativePaintPopUpButton
  (JNIEnv *, jclass, jintArray, jint, jint, jfloat, jfloat, jboolean, jint, jint, jint, jint);

/*
 * Class:     org_violetlib_jnr_aqua_impl_AquaNativePainter
 * Method:    nativePaintTableColumnHeader
 * Signature: ([IIIFFIIZI)V
 */
JNIEXPORT void JNICALL Java_org_violetlib_jnr_aqua_impl_AquaNativePainter_nativePaintTableColumnHeader
  (JNIEnv *, jclass, jintArray, jint, jint, jfloat, jfloat, jint, jint, jboolean, jint);

/*
 * Class:     org_violetlib_jnr_aqua_impl_AquaNativePainter
 * Method:    nativePaintSlider
 * Signature: ([IIIFFIIIZDII)V
 */
JNIEXPORT void JNICALL Java_org_violetlib_jnr_aqua_impl_AquaNativePainter_nativePaintSlider
  (JNIEnv *, jclass, jintArray, jint, jint, jfloat, jfloat, jint, jint, jint, jboolean, jdouble, jint, jint);

/*
 * Class:     org_violetlib_jnr_aqua_impl_AquaNativePainter
 * Method:    nativePaintSpinnerArrows
 * Signature: ([IIIFFIIZZ)V
 */
JNIEXPORT void JNICALL Java_org_violetlib_jnr_aqua_impl_AquaNativePainter_nativePaintSpinnerArrows
  (JNIEnv *, jclass, jintArray, jint, jint, jfloat, jfloat, jint, jint, jboolean, jboolean);

/*
 * Class:     org_violetlib_jnr_aqua_impl_AquaNativePainter
 * Method:    nativePaintSplitPaneDivider
 * Signature: ([IIIFFIIII)V
 */
JNIEXPORT void JNICALL Java_org_violetlib_jnr_aqua_impl_AquaNativePainter_nativePaintSplitPaneDivider
  (JNIEnv *, jclass, jintArray, jint, jint, jfloat, jfloat, jint, jint, jint, jint);

/*
 * Class:     org_violetlib_jnr_aqua_impl_AquaNativePainter
 * Method:    nativePaintTitleBar
 * Signature: ([IIIFFIIIIIZZ)V
 */
JNIEXPORT void JNICALL Java_org_violetlib_jnr_aqua_impl_AquaNativePainter_nativePaintTitleBar
  (JNIEnv *, jclass, jintArray, jint, jint, jfloat, jfloat, jint, jint, jint, jint, jint, jboolean, jboolean);

/*
 * Class:     org_violetlib_jnr_aqua_impl_AquaNativePainter
 * Method:    nativePaintScrollBar
 * Signature: ([IIIFFIIIFF)V
 */
JNIEXPORT void JNICALL Java_org_violetlib_jnr_aqua_impl_AquaNativePainter_nativePaintScrollBar
  (JNIEnv *, jclass, jintArray, jint, jint, jfloat, jfloat, jint, jint, jint, jfloat, jfloat);

/*
 * Class:     org_violetlib_jnr_aqua_impl_AquaNativePainter
 * Method:    nativeGetTitleBarButtonLayoutInfo
 * Signature: ([II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_violetlib_jnr_aqua_impl_AquaNativePainter_nativeGetTitleBarButtonLayoutInfo
  (JNIEnv *, jclass, jintArray, jint);

/*
 * Class:     org_violetlib_jnr_aqua_impl_AquaNativePainter
 * Method:    nativeGetSliderThumbBounds
 * Signature: ([FFFIIDII)V
 */
JNIEXPORT void JNICALL Java_org_violetlib_jnr_aqua_impl_AquaNativePainter_nativeGetSliderThumbBounds
  (JNIEnv *, jclass, jfloatArray, jfloat, jfloat, jint, jint, jdouble, jint, jint);

/*
 * Class:     org_violetlib_jnr_aqua_impl_AquaNativePainter
 * Method:    nativeDetermineButtonFixedHeight
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_org_violetlib_jnr_aqua_impl_AquaNativePainter_nativeDetermineButtonFixedHeight
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_violetlib_jnr_aqua_impl_AquaNativePainter
 * Method:    nativeDetermineButtonFixedWidth
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_org_violetlib_jnr_aqua_impl_AquaNativePainter_nativeDetermineButtonFixedWidth
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_violetlib_jnr_aqua_impl_AquaNativePainter
 * Method:    nativeDetermineSegmentedButtonFixedHeight
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_violetlib_jnr_aqua_impl_AquaNativePainter_nativeDetermineSegmentedButtonFixedHeight
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
